"""empty message

Revision ID: 155bdc13b935
Revises: 497bc84dfa18
Create Date: 2023-02-27 10:43:06.549009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155bdc13b935'
down_revision = '497bc84dfa18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lucky_numbers', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='family_pkey'),
    sa.UniqueConstraint('first_name', name='family_first_name_key')
    )
    # ### end Alembic commands ###
