"""empty message

Revision ID: 497bc84dfa18
Revises: 1a4ae64c411d
Create Date: 2023-02-13 16:26:25.114184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497bc84dfa18'
down_revision = '1a4ae64c411d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('lucky_numbers', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family')
    # ### end Alembic commands ###
